name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Merge updates from upstream 'main' branch
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git remote add upstream https://github.com/original-owner/repo.git
          git fetch upstream
          git merge upstream/main
